### ISSUE TITLE
Help to update the NPM packages

### ISSUE THREAD

**Issue by dalenguyen** [dalenguyen/WebdriverIO-TypeScript-Boilerplate#4]
Some of the packages in the project are outdates. It would be great if someone can help to update them.

**Comment by labsvisual** [comment]
@dalenguyen, I'd like to lend a hand keeping with the spirit of Hacktoberfest! 😄

**Comment by k-awe-some** [comment]
Hey Dale can I take it? Would love to have a chance to challenge myself with TypeScript 🚀

**Comment by dalenguyen** [comment]
@labsvisual Sorry Shreyansh, this looks like an overkill for you to help. I will let @k-awe-some handle this task. Thanks for your support :)

**Comment by k-awe-some** [comment]
@dalenguyen thank you!
